'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FfE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_drive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_drive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_photo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_photo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_usage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_usage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property barra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btn_contraer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_contraer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btn_expandir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_expandir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property car_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("car_photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coche_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coche_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property data_export() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_export", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property data_import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property del_channel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("del_channel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property del_channel2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("del_channel2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property del_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("del_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property del_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("del_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property del_usage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("del_usage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_car() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_car", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_drive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_drive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_person() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_person", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find_drive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find_drive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find_excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find_excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_first() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_first", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NetByte_Design_Studio___0007() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 0007", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NetByte_Design_Studio___00071() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 00071", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NetByte_Design_Studio___00072() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 00072", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NetByte_Design_Studio___0058() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 0058", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NetByte_Design_Studio___0072() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 0072", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_drive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_drive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_rule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_rule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_usage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_usage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property test() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("test", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_data() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_data", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
